try {
    console.log(a)
} 
catch (error) {
    console.log(`You haven't declared this before`)
}
finally{
    console.log("I am sorry")
}