console.log("This is try and catch method to handle errors")
let age = 21;
let a
try {
    console.log(a)
} 
catch (error) {
    console.log(`You haven't declared this before`)
}
finally{
    console.log("I am sorry")
}
if (age>18) {
    throw 
}